version: '3.8'

services:
  api:
    image: api
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 8080:8080
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api
