version: '3.8'

services:
  api:
    image: api
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 8080:8080
    environment:
      DB_USER: &db_user postgres
      DB_PASSWORD: &db_password password
      DB_NAME: &db_name api
      DB_HOST: db
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: *db_user
      POSTGRES_PASSWORD: *db_password
      POSTGRES_DB: *db_name
    ports:
      - 5432:5432
